// src/layouts/Header.vue
<template>
  <header>
    <div class="container container-flex-center-between">
      <div class="header-logo">
        <img :src="imageLogo" alt="logo oliveira" />
      </div>
      <div class="container-flex-center-between">
        <img class="account-img" :src="account" alt="account" />
        <span class="account-name" v-text="accountUser"></span>
        <App-Button variation="icone">
          <LogoutIcon :size="18" fillColor="var(--color-default)"/>
        </App-Button>
      </div>
    </div>
  </header>
</template>

<script>
import imageLogo from "../assets/img/logo-full.png";
import account from "../assets/img/account.png";

export default {
  name: "App-Header",
  props: {
    accountUser: {
      type: String,
    },
  },
  data: () => {
    return {
      imageLogo,
      account,
    };
  },
};
</script>

<style scoped>
header {
  background-color: var(--color-white);
  padding: 1.5rem 0;
  margin-bottom: 3rem;
}

.header-logo img {
  margin-right: 0.5rem;
  width: 15rem;
}

.account-name {
  font-weight: var(--weight-bold);
}

.account-img {
  width: 2rem;
  margin-right: 0.5rem;
}
</style>

// src/components/shared/header/Header.tsx
import React from 'react';
import './Header.css';
import type { IUser } from '../../../models/user.interface';
import axios from 'axios';
import { LogOut, UserRound } from 'lucide-react';

const Header: React.FC = () => {
  return (
    <header className="w-full flex items-center justify-between bg-white px-15 py-3 shadow-md">
      <img
        src="oliveira-trust-logo.png"
        alt="Oliveira Trust Logo"
        className="h-8"
      />
      <div className="flex items-center gap-2">
        <div className="flex items-center gap-1">
          <UserRound className="rounded-full border-1 border-solid mr-1" />
          <h1 className="text-xs font-bold">Felipe Mattos</h1>
        </div>
        <LogOut className="ml-3 size-4" />
      </div>
    </header>
  );
};

export default Header;
