// desafio-frontend-react/src/Pages/Home/components/FormDeleteWallet/FormDeleteWallet.tsx
import { Modal } from "../../../../components/Modal/Modal";
import { useWalletContext } from "../../../../contex/walletContext";
import { ModalDeleteProps } from "../../../../types/modal";

import styles from "./FormDeleteWallet.module.css";

export function FormDeleteWallet({
  id,
  openModalDelete,
  setOpenModalDelete,
}: ModalDeleteProps) {
  const { deleteUser } = useWalletContext();

  return (
    <Modal
      isOpen={openModalDelete}
      setOpenModal={() => {
        setOpenModalDelete(!setOpenModalDelete);
      }}
    >
      <form className={styles.formValidation}>
        <div className={styles.formDescriptions}>
          <span className={`${styles.formTrash} pi pi-trash`}></span>
          <span className={styles.formDescriptionOne}>Excluir Carteira</span>
          <span className={styles.formDescriptionTwo}>
            Tem certeza que deseja excluir essa Carteira?
          </span>
          <span className={styles.formDescriptionThree}>
            Está ação não poderá ser desfeita
          </span>
        </div>
        <div className={styles.buttonFinishDelete}>
          <button
            className={styles.buttonDelete}
            onClick={() => {
              deleteUser(id);
            }}
          >
            Excluir
          </button>
          <button className={styles.buttonToCancel}>Cancelar</button>
        </div>
      </form>
    </Modal>
  );
}

// src/Pages/Home/components/FormDeleteWallet/FormDeleteWallet.vue
<style src="./FormDeleteWallet.css"></style>

<template>
  <form class="formValidation" @submit.prevent="">
    <div class="formDescriptions">
      <span class="formTrash pi pi-trash"></span>
      <span class="formDescriptionOne">Excluir Carteira</span>
      <span class="formDescriptionTwo"
        >Tem certeza que deseja excluir essa Carteira?</span
      >
      <span class="formDescriptionThree"
        >Está ação não poderá ser desfeita</span
      >
    </div>
    <div class="buttonFinishDelete">
      <button class="buttonDelete" @click.stop="excluirUsuario(userId)">
        Excluir
      </button>
      <button class="buttonToCancel" @click="close">Cancelar</button>
    </div>
  </form>
</template>
<script>
import Users from "../../../../services/users.js";

export default {
  name: "FormDeleteWallet",
  props: {
    userId: String,
  },
  methods: {
    close() {
      this.$emit("close");
    },
    excluirUsuario() {
      Users.deletar(this.userId)
        .then(() => {
          this.$emit("walletUpdated");
          this.$emit("deleteSuccess");
          this.openedModalDelete = false;
        })
        .catch((error) => {
          console.error("Erro ao excluir usuário:", error);
        });
    },
  },
};
</script>
