// src/Pages/Home/components/FormEditWallet/FormEditWallet.vue
<style src="./FormEditWallet.css"></style>

<template>
  <div>
    <form class="formValidation" @submit.prevent="onSubmit">
      <input
        v-model="user.nome"
        placeholder="Nome"
        id="nome"
        name="input_nome"
      />
      <p class="errorMessage" v-if="errors.nome">{{ errors.nome }}</p>
      <input
        v-model="user.sobrenome"
        placeholder="Sobrenome"
        id="sobrenome"
        name="input_sobrenome"
      />
      <p class="errorMessage" v-if="errors.sobrenome">
        {{ errors.sobrenome }}
      </p>
      <input
        v-model="user.email"
        placeholder="E-mail"
        id="email"
        name="input_email"
      />
      <p class="errorMessage" v-if="errors.email">{{ errors.email }}</p>
      <div class="valuePurchase">
        <input
          v-model="user.valor_carteira"
          placeholder="Valor de Compra(Numeros)"
          id="valor_carteira"
          name="input_valor_carteira"
          maxlength="9"
          pattern="[0-9]+"
        />
        <span class="textBTC">BTC {{ btcValue.toFixed(9).slice(0, 9) }}</span>
      </div>
      <p class="errorMessage" v-if="errors.valor_carteira">
        {{ errors.valor_carteira }}
      </p>
      <div class="buttonFinish">
        <button class="buttonCancel" type="button" @click="close">
          Cancelar
        </button>
        <button class="buttonToAdd" type="submit">
          Adicionar
        </button>
      </div>
    </form>
  </div>
</template>
<script>
import Users from "../../../../services/users.js";
import Moedas from "../services/moedas.js";

export default {
  name: "FormEditWallet",
  props: {
    userEdit: {
      type: Object,
    },
  },
  data() {
    return {
      errors: [],
      user: {
        id: this.userEdit.id,
        nome: this.userEdit.nome,
        sobrenome: this.userEdit.sobrenome,
        email: this.userEdit.email,
        valor_carteira: this.userEdit.valor_carteira,
      },
      btcValue: 0,
    };
  },
  watch: {
    "user.valor_carteira": function(novoValor) {
      this.listarMoedas(novoValor);
    },
  },

  methods: {
    close() {
      this.$emit("close");
    },

    listarMoedas(novoValor) {
      Moedas.listarMoeda().then((resposta) => {
        const novovalorBtc = novoValor / resposta.data.BTCBRL.bid;
        this.btcValue = novovalorBtc;
      });
    },

    listar() {
      Users.listar().then((resposta) => {
        this.users = resposta.data;
      });
    },

    onSubmit() {
      this.errors = {};

      const nomeRegex = /^[a-zA-ZÀ-ÿ]+( [a-zA-ZÀ-ÿ]+)*$/;
      const sobrenomeRegex = /^[a-zA-ZÀ-ÿ]+( [a-zA-ZÀ-ÿ]+)*$/;
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      const valor_carteiraRegex = /^\d+(\.\d{1,5})?$/;

      const trimmedNome = this.user.nome ? this.user.nome.trim() : "";
      const trimmedSobreNome = this.user.sobrenome
        ? this.user.sobrenome.trim()
        : "";
      const trimmedEmail = this.user.email ? this.user.email.trim() : "";
      const trimmedvalor_carteira = this.user.valor_carteira
        ? this.user.valor_carteira.trim()
        : "";

      if (!trimmedNome) {
        this.errors.nome = "Nome obrigatório!";
      } else if (!nomeRegex.test(trimmedNome)) {
        this.errors.nome =
          "Nome inválido. Por favor, digite apenas caracteres.";
      }

      if (!trimmedSobreNome) {
        this.errors.sobrenome = "Sobrenome obrigatório!";
      } else if (!sobrenomeRegex.test(trimmedSobreNome)) {
        this.errors.sobrenome =
          "Nome inválido. Por favor, digite apenas caracteres.";
      }

      if (!trimmedEmail) {
        this.errors.email = "E-mail obrigatório!";
      } else if (!emailRegex.test(trimmedEmail)) {
        this.errors.email = "E-mail inválido!";
      }

      if (!trimmedvalor_carteira) {
        this.errors.valor_carteira = "Valor de compra obrigatório!";
      } else if (!valor_carteiraRegex.test(trimmedvalor_carteira)) {
        this.errors.valor_carteira =
          "Valor de compra inválido. Digite apenas valores numéricos.";
      }

      if (Object.keys(this.errors).length === 0) {
        this.user.valor_carteira = this.btcValue.toFixed(5);
        let formValidation = {
          nome: trimmedNome,
          sobrenome: trimmedSobreNome,
          email: trimmedEmail,
          valor_carteira: this.user.valor_carteira,
        };
        this.$emit("formValidation", formValidation);

        Users.atualizar(this.user).then(() => {
          this.$emit("walletUpdated");
          this.$emit("updateSuccess");
          this.user.nome = null;
          this.user.sobrenome = null;
          this.user.email = null;
          this.user.valor_carteira = null;
        });
      }
    },
  },
};
</script>

// src/Pages/Home/components/FormEditWallet/FormEditWallet.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { Modal } from "../../../../components/Modal/Modal";
import { useForm } from "react-hook-form";

import Users from "../../../../services/users.tsx";
import Modedas from "../services/moedas.tsx";

import styles from "./FormEditWallet.module.css";

import { ModalEditProps } from "../../../../types/modal";
import { useState } from "react";
import { useWalletContext } from "../../../../contex/walletContext";
import {
  ProfileSchema,
  profileSchema,
} from "../../../../validation/SchemaValidation.ts";

export function FormEditWallet({
  user,
  openModalEdit,
  setOpenModalEdit,
}: ModalEditProps) {
  const [btcValue, setBTCValue] = useState<number | null>(null);

  const { fetchUsers } = useWalletContext();

  const {
    reset,
    formState: { errors },
    register,
    handleSubmit,
  } = useForm<ProfileSchema>({
    resolver: zodResolver(profileSchema),
  });

  function handleAddWallet(data: ProfileSchema) {
    listCoins(data.valor_carteira).then((valueBTC) => {
      const btcValueFormatted = parseFloat(valueBTC.toFixed(8));
      const id = user.id;
      const addWallet = { ...data, valor_carteira: btcValueFormatted };

      Users.atualizar(addWallet, id).then(() => {
        setOpenModalEdit(false);
        reset();
        setBTCValue(null);
        fetchUsers();
      });
    });
  }

  function listCoins(value: number) {
    return Modedas.listarMoeda().then((res) => {
      return value / res.data.BTCBRL.bid;
    });
  }

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = parseFloat(event.target.value);
    if (!isNaN(value)) {
      listCoins(value).then((valueBTC) => {
        setBTCValue(valueBTC);
      });
    } else {
      setBTCValue(null);
    }
  };

  return (
    <div className={styles.bodyModal}>
      <Modal
        isOpen={openModalEdit}
        setOpenModal={() => {
          setOpenModalEdit(!setOpenModalEdit);
        }}
      >
        <form
          onSubmit={handleSubmit(handleAddWallet)}
          className={styles.formValidation}
        >
          <p className={styles.textValidation}>Adicionar Carteira</p>
          <input
            id="nome"
            placeholder="Nome"
            {...register("nome")}
            defaultValue={user?.nome}
          />
          {errors.nome && <p className={styles.erros}>{errors.nome.message}</p>}
          <input
            id="sobrenome"
            placeholder="Sobrenome"
            {...register("sobrenome")}
            defaultValue={user?.sobrenome}
          />
          {errors.sobrenome && (
            <p className={styles.erros}>{errors.sobrenome.message}</p>
          )}
          <input
            id="email"
            placeholder="E-mail"
            {...register("email")}
            defaultValue={user?.email}
          />
          {errors.email && (
            <p className={styles.erros}>{errors.email.message}</p>
          )}
          <div className={styles.valorDeCompra}>
            <input
              id="valor_carteira"
              placeholder="Valor de compra(Números)"
              {...register("valor_carteira")}
              onChange={handleChange}
              defaultValue={user?.valor_carteira}
            />
            <span className={styles.textBTC}>
              BTC
              {""}
              {btcValue !== null ? `${btcValue.toFixed(8)}` : ""}
            </span>
          </div>
          {errors.valor_carteira && (
            <p className={styles.erros}>{errors.valor_carteira.message}</p>
          )}
          <div className={styles.buttonFinish}>
            <button
              className={styles.buttonCancel}
              type="button"
              onClick={() => setOpenModalEdit(false)}
            >
              Cancelar
            </button>
            <button className={styles.buttonToAdd} type="submit">
              Adicionar
            </button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
