// src/components/shared/delete-user-modal/DeleteUserModal.tsx
import { Trash } from 'lucide-react';
import React from 'react';

interface DeleteUserModalProps {
  onClose: () => void;
  onDelete: () => void;
}

const DeleteUserModal = ({ onClose, onDelete }: DeleteUserModalProps) => {
  return (
    <div className="p-4 flex flex-col items-center m-auto p-10">
      <div className="rounded-full border-1 border-solid border-red-500 w-12 h-12 flex items-center justify-center mb-4">
        <Trash className="text-red-500 font-bold text-lg" />
      </div>
      <h2 className="text-lg font-bold mb-2">Excluir Carteira</h2>
      <p className="mb-4 text-center">
        Tem certeza de que deseja excluir esta carteira?
        <br />
        Esta ação não poderá ser desfeita.
      </p>
      <div className="flex flex-col space-y-2 w-full">
        <button
          className="px-4 py-2 bg-red-500 text-white rounded font-semibold hover:bg-red-600"
          onClick={() => onDelete()}
        >
          Excluir
        </button>
        <button
          className="px-4 py-2 text-blue-500 rounded hover:bg-blue-500 hover:text-white border border-blue-500"
          onClick={() => onClose()}
        >
          Cancelar
        </button>
      </div>
    </div>
  );
};

export default DeleteUserModal;

// src/components/feature/modals/DeleteUserModal.vue
<script setup lang="ts">
import Modal from '../../common/CommonModal.vue'
import Button from '../../common/CommonButton.vue'
import TextButton from '../../common/TextButton.vue'
import { useAppStore } from '@/stores'
import type { User } from '@/types/user.type'

interface Props {
  user: User
  isOpen?: boolean
  title?: string
}

const store = useAppStore()

const emit = defineEmits(['close'])
const props = defineProps<Props>()

const close = () => {
  emit('close')
}

const deleteUser = async () => {
  await store.deleteUser(props.user.id)
  close()
}
</script>

<template>
  <div class="delete-user-modal">
    <Modal v-show="isOpen" @close="close">
      <template v-slot:body>
        <div class="py-10 flex flex-col justify-center items-center text-center">
          <div class="border-4 border-red-500 rounded-full mb-6">
            <font-awesome-icon
              class="pl-4 pr-4 py-3 fill-red-500"
              :icon="['fas', 'trash']"
              style="color: red; font-size: 2em"
            />
          </div>
          <h2 class="mb-1">Excluir Carteira</h2>
          <p class="m-0.5">Tem certeza que deseja excluir essa Carteira?</p>
          <p>Essa ação não poderá ser desfeita.</p>
          <div class="mt-5 flex flex-col justify-center items-center w-full">
            <Button class="w-11/12 m-2.5" :danger="true" @onClick="deleteUser" label="Excluir" />
            <TextButton class="m-2.5" @onClick="close" label="Cancelar" />
          </div>
        </div>
      </template>
    </Modal>
  </div>
</template>
