// src/components/Header/Header.vue
<style>
@import "./Header.css";
</style>

<template>
  <div class="headerContainer">
    <img
      class="logo"
      src="./assets/img/logo-ot.png"
      alt="Logo Oliveira Trust"
    />
    <div class="headerLogin">
      <button class="headerButtonLogin">
        <img src="./assets/svg/user-icon.svg" alt="Icone Usuário" />
        <span class="userName">Otávio Oliveira</span>
      </button>
      <button class="headerButtonLogOut">
        <span class="pi pi-sign-out" style="color: #767676"></span>
      </button>
    </div>
  </div>
</template>

// src/components/Header/Header.tsx
import styles from "./Header.module.css";

import logo from "../../assets/img/logo-ot.png";
import userIcon from "../../assets/svg/user-icon.svg";

import "primeicons/primeicons.css";

export function Header() {
  return (
    <div className={styles.headerContainer}>
      <img className={styles.logo} src={logo} alt="Logo Oliveira Trust" />
      <div className={styles.headerLogin}>
        <button className={styles.headerButtonLogin}>
          <img src={userIcon} alt="Icone Usuário" />
          <span className={styles.userName}>Otávio Oliveira</span>
        </button>
        <button className={styles.headerButtonLogOut}>
          <span className="pi pi-sign-out" style={{ color: "#767676" }}></span>
        </button>
      </div>
    </div>
  );
}
