// src/components/Header/index.vue
<!-- Componente Header -->
<template>
  <header>
    <img :src="svgUrl" alt="Logo" class="logo" />

    <div class="user">
      <i class="pi pi-user user-svg"></i>
      <span class="user-name">Otávio Oliveira</span>
      <i class="pi pi-sign-out exit-svg"></i>
    </div>
  </header>
</template>

<script>
import svg from '@/assets/brand.svg'

export default {
  name: 'Header',
  components: {
  },
  data() {
    return {
      svgUrl: svg,
    }
  },
}
</script>

<style scoped>
@import './styles.css';
</style>

// src/components/header/header.tsx


import image from '../../assets/logo.svg';
import { FiLogOut } from 'react-icons/fi';
import { BiUserCircle } from 'react-icons/bi';

import '../header/header.css';

const Header = ( ) => { 
return (
  <header>
    <nav>
      <div className='logo'>
        <img src={ image } alt='image' />
      </div>

      <div className='user'>
        <BiUserCircle />
        <b> Joao Paulo Gardiano </b>
        <button> <FiLogOut /> </button>
      </div>
    </nav>
  </header>
  );
}

export default Header;
