// src/components/Header/Header.tsx
import styles from "./Header.module.css";

import logo from "../../assets/img/logo-ot.png";
import userIcon from "../../assets/svg/user-icon.svg";

import "primeicons/primeicons.css";

export function Header() {
  return (
    <div className={styles.headerContainer}>
      <img className={styles.logo} src={logo} alt="Logo Oliveira Trust" />
      <div className={styles.headerLogin}>
        <button className={styles.headerButtonLogin}>
          <img src={userIcon} alt="Icone Usuário" />
          <span className={styles.userName}>Otávio Oliveira</span>
        </button>
        <button className={styles.headerButtonLogOut}>
          <span className="pi pi-sign-out" style={{ color: "#767676" }}></span>
        </button>
      </div>
    </div>
  );
}

// src/components/Header/index.vue
<!-- Componente Header -->
<template>
  <header>
    <img :src="svgUrl" alt="Logo" class="logo" />

    <div class="user">
      <i class="pi pi-user user-svg"></i>
      <span class="user-name">Otávio Oliveira</span>
      <i class="pi pi-sign-out exit-svg"></i>
    </div>
  </header>
</template>

<script>
import svg from '@/assets/brand.svg'

export default {
  name: 'Header',
  components: {
  },
  data() {
    return {
      svgUrl: svg,
    }
  },
}
</script>

<style scoped>
@import './styles.css';
</style>
