// src/Pages/Home/components/SearchWallet/SearchWallet.vue
<style src="./SearchWallet.css"></style>
<template>
  <div>
    <slot name="searchWallet"> </slot>
    <form class="searchValidation" @submit.prevent="onSubmit">
      <div class="searchDivInput">
        <input v-model="nome" placeholder="Nome" id="name" name="input_name" />
        <p class="searchErrorMessage" v-if="errors.nome">{{ errors.nome }}</p>
      </div>
      <div class="searchDivInput">
        <input
          v-model="sobrenome"
          placeholder="Sobrenome"
          id="sobrenome"
          name="input_sobrenome"
        />
        <p class="searchErrorMessage" v-if="errors.sobrenome">
          {{ errors.sobrenome }}
        </p>
      </div>
      <div class="searchDivInput">
        <input
          v-model="email"
          placeholder="E-mail"
          id="email"
          name="input_email"
        />
        <p class="searchErrorMessage" v-if="errors.email">{{ errors.email }}</p>
      </div>
      <div class="searchDivButton">
        <button class="buttonSearch pi pi-search">Buscar</button>
      </div>
    </form>
  </div>
</template>

<script>
export default {
  name: "SearchWallet",

  methods: {
    onSubmit() {
      this.errors = {};

      const nomeRegex = /^[a-zA-ZÀ-ÿ]+$/;
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

      const trimmedNome = this.nome ? this.nome.trim() : "";
      const trimmedSobreNome = this.sobrenome ? this.sobrenome.trim() : "";
      const trimmedEmail = this.email ? this.email.trim() : "";

      if (trimmedNome && !nomeRegex.test(trimmedNome)) {
        this.errors.nome =
          "Nome inválido. Por favor, digite apenas caracteres.";
      }

      if (trimmedSobreNome && !nomeRegex.test(trimmedSobreNome)) {
        this.errors.sobrenome =
          "Sobrenome inválido. Por favor, digite apenas caracteres.";
      }

      if (trimmedEmail && !emailRegex.test(trimmedEmail)) {
        this.errors.email =
          "E-mail inválido. Por favor, digite o e-mail corretamente.";
      }

      if (Object.keys(this.errors).length === 0) {
        let searchCriteria = {
          nome: trimmedNome,
          sobrenome: trimmedSobreNome,
          email: trimmedEmail,
        };

        this.$emit("search", searchCriteria);

        this.nome = null;
        this.sobrenome = null;
        this.email = null;
      }
    },
  },
  data() {
    return {
      nome: null,
      sobrenome: null,
      email: null,
      errors: [],
      users: [],
    };
  },
};
</script>

// src/Pages/Home/components/SearchWallet/SearchWallet.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useForm } from "react-hook-form";

import styles from "./SearchWallet.module.css";

const searchSchema = z.object({
  nome: z.string(),
  sobrenome: z.string(),
  email: z.string(),
});

type SearchSchema = z.infer<typeof searchSchema>;

export function SearchWallet({ setSearchResults }: any) {
  const {
    reset,
    formState: { errors },
    register,
    handleSubmit,
  } = useForm<SearchSchema>({
    resolver: zodResolver(searchSchema),
  });

  function handleAddWallet(data: SearchSchema) {
    console.log(data);
    setSearchResults(data);
    reset();
  }

  return (
    <div>
      <form
        onSubmit={handleSubmit(handleAddWallet)}
        className={styles.searchValidation}
      >
        <div className="searchDivInput">
          <input
            id="nome"
            placeholder="Nome"
            type="text"
            {...register("nome")}
          />
          {errors.nome && <p className={styles.erros}>{errors.nome.message}</p>}
        </div>
        <div className={styles.searchDivInput}>
          <input
            id="sobrenome"
            placeholder="Sobrenome"
            type="text"
            {...register("sobrenome")}
          />
          {errors.sobrenome && (
            <p className={styles.erros}>{errors.sobrenome.message}</p>
          )}
        </div>
        <div className={styles.searchDivInput}>
          <input
            id="email"
            placeholder="E-mail"
            type="text"
            {...register("email")}
          />
          {errors.email && (
            <p className={styles.erros}>{errors.email.message}</p>
          )}
        </div>
        <div className={styles.searchDivButton}>
          <button className={`${styles.buttonSearch}  `}>
            <i className="pi pi-search" style={{ paddingRight: "10px" }}></i>
            Buscar
          </button>
        </div>
      </form>
    </div>
  );
}
