// src/components/header/header.tsx


import image from '../../assets/logo.svg';
import { FiLogOut } from 'react-icons/fi';
import { BiUserCircle } from 'react-icons/bi';

import '../header/header.css';

const Header = ( ) => { 
return (
  <header>
    <nav>
      <div className='logo'>
        <img src={ image } alt='image' />
      </div>

      <div className='user'>
        <BiUserCircle />
        <b> Joao Paulo Gardiano </b>
        <button> <FiLogOut /> </button>
      </div>
    </nav>
  </header>
  );
}

export default Header;

// src/layouts/HomeLayout/components/Header.vue
<template>
    <header class="home-header">
        <div class="container">
            <h1><img :src="image" />BTC Carteiras</h1>
            <button class="btn btn-default" @click.prevent="redirect('/')">
                Adicionar carteira
            </button>
        </div>
    </header>
</template>

<script>
export default {
    data() {
        return {
            image: require('@/assets/img/logo.svg'),
        }
    },
}
</script>

<style>
</style>
